---
# - name: Download the stable docker-compose
#   shell: curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

# - name: Apply executable permissions to the binary
#   shell: chmod +x /usr/local/bin/docker-compose

- name: Clone git project
  git:
    repo: '{{ repo_url }}'
    dest: /home/application

- name: Run docker-compose
  shell: 
    cmd: docker-compose run web django-admin.py startproject composeexample .
    chdir: /home/application/
  register: output
  ignore_errors: True
  changed_when:
    - output.rc != 0 or output.rc != 1

# - name: Docker-compose up
#   shell: docker-compose up
#   ignore_errors: True
#   changed_when:
#     - output.rc != 0 or output.rc != 1

- name: Run `docker-compose up` again
  docker_compose:
    project_src: application_web_1
    build: no
  register: output

- debug:
    var: output